server:
  port: 8080
spring:
  application:
    name: application
#  profiles:
#    active:
#      - ${SPRING_PROFILES_ACTIVE:@activatedProperties@}
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_context_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
SpringDoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
security:
  jwt:
    secret: "firestormfirestormfirestormfirestormfirestormfirestorm"
    expires-date: 2
    issuer: http://localhost:${server.port}